spring.application.name=CafeFinderBackend

spring.datasource.url=jdbc:postgresql://localhost:5433/cafe
spring.datasource.username=postgres
spring.datasource.password=toughgirlmask2912

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
